### ISSUE TITLE
Issue after get package from pub dev

### ISSUE THREAD

**Issue by sylvestrevgen** [weishirongzhen/flutter_trust_wallet_core#24]
After get flutter_trust_wallet_core package from pub dev, trust_wallet_core_ffi.dart file is not defined, only flutter_trust_wallet_core.dart is defined.

**Comment by weishirongzhen** [comment]
this flutter_trust_wallet_core is not public to pub.dev yet. pub.dev's one  is not from this repo. Please checkout this  repo locally.
