### ISSUE TITLE
Problem with build on android (credentials are not valid to auth to maven.pkg.github.com/weishirongzhen repo)

### ISSUE THREAD

**Issue by remboshelby** [weishirongzhen/flutter_trust_wallet_core#30]
**Description:** I try to make APK for android, then Gradle compiler starting download library artifact, something goes wrong (compiler cannot get access by credentials from source file, to repository where artifact kept)

**Error report:**
`FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Could not determine the dependencies of task ':app:lintVitalRelease'.   
> Could not resolve all artifacts for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.weishirongzhen:wallet-core:2.6.20.           
     Required by:                                                       
         project :app > project :trust_wallet_core                      
      > Could not resolve com.weishirongzhen:wallet-core:2.6.20.        
         > Could not get resource 'https://maven.pkg.github.com/weishirongzhen/wallet-core/com/weishirongzhen/wallet-core/2.6.20/wallet-core-2.6.20.pom'.
            > Could not GET 'https://maven.pkg.github.com/weishirongzhen/wallet-core/com/weishirongzhen/wallet-core/2.6.20/wallet-core-2.6.20.pom'. Received status code 400 from server: Bad Request
`

**Expected behavior:**: Success apk build.

**Probable solution:**
As much as I understand credentials that placed in trust_wallet_core file became not valid.
Can you update them?

**Comment by weishirongzhen** [comment]
> **Description:** I try to make APK for android, then Gradle compiler starting download library artifact, something goes wrong (compiler cannot get access by credentials from source file, to repository where artifact kept)
> 
> **Error report:** `FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Could not determine the dependencies of task ':app:lintVitalRelease'.
> 
> > Could not resolve all artifacts for configuration ':app:debugRuntimeClasspath'.
> > Could not resolve com.weishirongzhen:wallet-core:2.6.20.
> > Required by:
> > project :app > project :trust_wallet_core
> > > Could not resolve com.weishirongzhen:wallet-core:2.6.20.
> > > Could not get resource 'https://maven.pkg.github.com/weishirongzhen/wallet-core/com/weishirongzhen/wallet-core/2.6.20/wallet-core-2.6.20.pom'.
> > > Could not GET 'https://maven.pkg.github.com/weishirongzhen/wallet-core/com/weishirongzhen/wallet-core/2.6.20/wallet-core-2.6.20.pom'. Received status code 400 from server: Bad Request
> > `
> 
> **Expected behavior:**: Success apk build.
> 
> **Probable solution:** As much as I understand credentials that placed in trust_wallet_core file became not valid. Can you update them?

updated

**Comment by weishirongzhen** [comment]
how?  credentials already set to no expoired.
there is a stable way, use  [https://github.com/weishirongzhen/flutter_trust_wallet_core_lib_include](https://github.com/weishirongzhen/flutter_trust_wallet_core_lib_include). this repo integrate lib locally.

**Comment by weishirongzhen** [comment]
don't konw why my new  key is deleted, update new credentials again.

**Comment by weishirongzhen** [comment]
> don't konw why my new key is deleted, update new credentials again.

I know why,  github secure policy, once credentials found in github repo, it will delete this key, I will find a way to solve this issue

**Comment by remboshelby** [comment]
Thank you very much for your help

**Comment by mHassan20896** [comment]
I am facing this issue again
