### ISSUE TITLE
How to create HDWallet by using privateKey?

### ISSUE THREAD

**Issue by remboshelby** [weishirongzhen/flutter_trust_wallet_core#31]
Hello. Your plugging is very useful. Thank you for it. 
Now Im trying create HDWallet from privateKey using method createWithData.
As I understood this method provides creation wallet using entropy.
Can you help me how to use this method with privateKey? or it is not impossible?

**Comment by weishirongzhen** [comment]
wallet core source alreay point out

`
/// Creates an HDWallet from entropy (corresponding to a mnemonic).
/// Null is returned on invalid input. Returned object needs to be deleted.
TW_EXPORT_STATIC_METHOD
struct TWHDWallet *_Nullable TWHDWalletCreateWithEntropy(TWData *_Nonnull entropy, TWString *_Nonnull passphrase);
`

entropy corresponding to a mnemonic, privateKey is not able to create "hdwallet".

**Comment by remboshelby** [comment]
Okey. Thank you for response.
