### ISSUE TITLE
Custom trustWallet

### ISSUE THREAD

**Issue by TagorePde** [weishirongzhen/flutter_trust_wallet_core#36]
I'm looking for a developer to do a custom institutional wallet, with some api integrations and also a custom wizard start.
Maybe here i can find? sorry is this is not the place.
regards.

**Comment by Selfcare-Trustwallet** [comment]
> I'm looking for a developer to do a custom institutional wallet, with some api integrations and also a custom wizard start.
> Maybe here i can find? sorry is this is not the place.
> regards.

Contact Trustwalletselfcare@consultant.com

**Comment by weishirongzhen** [comment]
```
maven {
            url = uri("https://maven.pkg.github.com/trustwallet/wallet-core")
            credentials {
                username = project.findProperty("gpr.user") ?: System.getenv("USERNAME")
                password = project.findProperty("gpr.key") ?: System.getenv("TOKEN")
            }
        }
```

set your own  correct credentials, then sync again
