### ISSUE TITLE
How to build flutter plugin by own via TrustWalletCore ?

### ISSUE THREAD

**Issue by jerrywangjing** [weishirongzhen/flutter_trust_wallet_core#42]
Because the flutter_trust_wallet_core lib i used, version is too low, and  i want to update ios and android walletCore lib, but one or more bugs caused in flutter plugin，so i want to update flutter plugin by my self, specific for c++ code in plugin.

please help me for build my own flutter trust wallet core lib, or recommand docs, think you!

**Comment by weishirongzhen** [comment]
this may help [READ.me](https://github.com/weishirongzhen/flutter_trust_wallet_core#readme)

**Comment by jerrywangjing** [comment]
i known this readme.me file, and now i also used, i mean is how to build walletCore code to dart code like files in lib dir, because i want to build my own flutter plugin.

**Comment by weishirongzhen** [comment]
fork this repo then follow https://docs.flutter.dev/development/packages-and-plugins/developing-packages#dart-only-platform-implementations step

**Comment by jerrywangjing** [comment]
ok, thinks your reply.

**Comment by jalchr** [comment]
@jerrywangjing were you able to do any updates ?
