### ISSUE TITLE
Couldn't resolve Failed to lookup symbol 'TWMnemonicIsValid': undefined symbol: TWMnemonicIsValid

### ISSUE THREAD

**Issue by baharmovahed** [weishirongzhen/flutter_trust_wallet_core#43]
Hi.
after cloning and compiling the example, I was faced with this error and couldn't solve it.

> The following ArgumentError was thrown building Builder:
> Invalid argument(s): Failed to lookup symbol 'TWMnemonicIsValid': undefined symbol: TWMnemonicIsValid

could you help me?

**Comment by weishirongzhen** [comment]
Did you build your own android aar lib?

**Comment by kayson3** [comment]
using this HDWallet(strength: 128, passphrase: "");
i got ArgumentError (Invalid argument(s): Failed to lookup symbol 'TWHDWalletCreate': undefined symbol: TWHDWalletCreate)

then using HDWallet.createWithMnemonic(mnemonic);
i got ArgumentError (Invalid argument(s): Failed to lookup symbol 'TWMnemonicIsValid': undefined symbol: TWMnemonicIsValid)

did not build android aar lib (i just installed from pubdev directly)

**Comment by flutterdevcodiste** [comment]
@kayson3 
I'm also getting the same error after a successful download from GitHub using username and app token.
Will you please help me how to resolve this in the demo app?

**Comment by jalchr** [comment]
> Did you build your own android aar lib?

@weishirongzhen How can I do that ?

**Comment by KubyWong** [comment]
I'm also getting the same error after a successful download from GitHub using username and app token.
Will you please help me how to resolve this in the demo app?

**Comment by flutterdevcodiste** [comment]
Hey @baharmovahed, have any of you found a solution? I'm also stuck here and can't proceed to deliver the app.

@weishirongzhen does it require to generate own build.?

**Comment by JKing1123** [comment]
> Hi. after cloning and compiling the example, I was faced with this error and couldn't solve it.
> 
> > The following ArgumentError was thrown building Builder:
> > Invalid argument(s): Failed to lookup symbol 'TWMnemonicIsValid': undefined symbol: TWMnemonicIsValid
> 
> could you help me?

I have the same problem. Have you solved it yet

**Comment by weishirongzhen** [comment]
you have to build you own android lib, or else will lookup failed. check https://github.com/weishirongzhen/flutter_trust_wallet_core/issues/26
or just run on ios
