### ISSUE TITLE
Could not get resource 'https://maven.pkg.github.com/trustwallet/wallet-core/com/trustwallet/wallet-core/2.7.2/wallet-core-2.7.2.pom'

### ISSUE THREAD

**Issue by kayson3** [weishirongzhen/flutter_trust_wallet_core#44]
Could not get resource 'https://maven.pkg.github.com/trustwallet/wallet-core/com/trustwallet/wallet-core/2.7.2/wallet-core-2.7.2.pom'.         
    > Username must not be null

even after adding this:

maven {
            url = uri("https://maven.pkg.github.com/trustwallet/wallet-core")
            credentials {
                username = project.findProperty("gpr.user") ?: System.getenv("USERNAME")
                password = project.findProperty("gpr.key") ?: System.getenv("TOKEN")
            }
        }

**Comment by weishirongzhen** [comment]
Set yourself gpr info or env variable
refer to [https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-gradle-registry#installing-a-package](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-gradle-registry#installing-a-package)

**Comment by TejaDroid** [comment]
@kayson3 
Hope you resolved your issue with Trustwallet,

If not then just replace your actual github user name and app access token in credentials as

maven {
    url = uri("https://maven.pkg.github.com/trustwallet/wallet-core")
    credentials {
        username = "<github account user name>"
        password = "<github app access token generated from app settings>"
    }
}

**Comment by kayson3** [comment]
Yes I did, Thanks
