### ISSUE TITLE
Everscale support

### ISSUE THREAD

**Issue by sylvestrevgenhiveon** [weishirongzhen/flutter_trust_wallet_core#50]
Hello. @weishirongzhen Please, can you update this plugin according to last trust wallet core lib? Everscale blockchain was added, fixes etc.🙏

**Comment by weishirongzhen** [comment]
> 

I'm doing it now, since wallet-core add many new api, but it will be last update before dart 2.19 release. Because dart 2.19 and  ffi-gen introduce many new api.

**Comment by sylvestrevgenhiveon** [comment]
I see that you update the package. Thank you so much for operative feedback👍
