### ISSUE TITLE
Username must not be null

### ISSUE THREAD

**Issue by codersangam** [weishirongzhen/flutter_trust_wallet_core#52]
I tried to generate token and place UN and token in build.gradle but got errors for android. iOS seems to work fine. I even tried your libs and your github un and token but got same error. 
<img width="695" alt="Screenshot 2022-12-25 at 2 03 52 PM" src="https://user-images.githubusercontent.com/66767187/209463891-e2167492-2108-4647-b06c-6b0723d7b185.png">

**Comment by weishirongzhen** [comment]
maven {
            url = uri("https://maven.pkg.github.com/trustwallet/wallet-core")
            credentials {
                username = project.findProperty("gpr.user") ?: System.getenv("USERNAME")
                password = project.findProperty("gpr.key") ?: System.getenv("TOKEN")
            }
        }


set your github credentials

**Comment by codersangam** [comment]
I used username and token after generating token but sill have same issue.
