### ISSUE TITLE
Problem with ffigen splitting modules

### ISSUE THREAD

**Issue by suxinjie** [weishirongzhen/flutter_trust_wallet_core#55]
Thank you for your efforts, your project helped me solve a big problem.

But I encountered a problem when using the project, I would like to ask you:

I ran the `dart run ffigen` command, and only one file was generated: `generated_bindings.dart`, this file has line 1.4w, and all the information is in this one file. Of course, I can use this file to run normally.

But I see that in your project, the files generated by ffi are divided into modules: `flutter_trust_wallet_core/tree/main/lib/ffi_impl`

I prefer this way of yours as it makes the code much clearer.

-----------------------------------------------

I checked how ffigen is used: https://pub.dev/packages/ffigen

I can't find a way to unpack it either.

-----------------------------------------------

Did you split it manually?

**Comment by weishirongzhen** [comment]
Yes, I split it manually.

**Comment by suxinjie** [comment]
Thank you for your efforts, I will imitate your way to continue to split @weishirongzhen

**Comment by suxinjie** [comment]
> Yes, I split it manually.


Thank you for your efforts, I will imitate your way to continue to split
